### ISSUE TITLE
PEX integration?

### ISSUE THREAD

**Issue by archenroot** [AlexIoannides/pyspark-example-project#11]
Hi guys, looking to template spark jobs as well, thx for this job!

What about PEX aproach?
https://medium.com/criteo-labs/packaging-code-with-pex-a-pyspark-example-9057f9f144f3

**Comment by AlexIoannides** [comment]
I'd prefer it if people forked this (simple) repo and implemented the use of PEX themselves, rather than be channeled into using it via this project.
