### ISSUE TITLE
YAML instead of JSON

### ISSUE THREAD

**Issue by archenroot** [AlexIoannides/pyspark-example-project#12]
JSON is very verbose for config only, I suggest to move to YAML:
https://github.com/sampsyo/confuse

**Comment by AlexIoannides** [comment]
YAML is a superset of JSON - it only **looks** different. 

Personally - after having spent days configuring Kubernetes deployments using YAML - I prefer JSON for basic config. Plus, I'd rather not have to introduce another dependency, if I don't have to (these can be problematic for some corporations that need to get approval for each and every package that they need to use).
