### ISSUE TITLE
Nice work! Could you please add the license file?

### ISSUE THREAD

**Issue by bambrozio** [AlexIoannides/pyspark-example-project#16]
Nice work! Could you please add the license file?
I was wondering if this is a MIT or Apache license. Cheers!

**Comment by AlexIoannides** [comment]
This is so high-level that I'm not sure it evens needs a license!

**Comment by rakaliku** [comment]
> Nice work! Could you please add the license file?
> I was wondering if this is a MIT or Apache license. Cheers!

@bambrozio Just wandering, for simple practice code , what should be my license file. please guide me.

My Github:- [https://github.com/rakaliku/PySpark ]

**Comment by AlexIoannides** [comment]
@rakaliku [This](https://opensource.org/licenses) is a useful resource.

**Comment by rakaliku** [comment]
if possible can you please check my GITHUB, and suggest me anything possible. I m a learner and not aware this license process actually,  It will great help for me. [https://github.com/rakaliku/PySpark](https://github.com/rakaliku/PySpark) 
@AlexIoannides

**Comment by bambrozio** [comment]
When you create a new repository, GitHub suggests you some default licenses you can use. Just select one (MIT is usually the one for free open-source).
[Here you have instructions](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) on how to do that for repos that already exist.
